services:
  web:
    image: php:8.2-apache
    container_name: lamp_template_web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:9.1
    env_file:
      - ./.env
    container_name: lamp_template_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_PW
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_db_user
      MYSQL_PASSWORD: lamp_PW
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: lamp_template_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: lamp_db_user
      PMA_PASSWORD: lamp_PW
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:

